### ISSUE TITLE
Incorrect config path creation when `XDG_CONFIG_HOME` is set

### ISSUE THREAD

**Issue by CIAvash** [lizmat/Zef-Configuration#1]
The issue is with [this line](https://github.com/lizmat/Zef-Configuration/blob/dd4fe13e1ec8e8cfdca31ec5abc5c0984910a7d3/lib/Zef/Configuration.rakumod#L419).

It adds `'.config'` to `XDG_CONFIG_HOME`, but it shouldn't add anything to it. If the variable is not set, it should add it to just `$*HOME`.

**Comment by lizmat** [comment]
Thanks for the spot.  Should be fixed with 0.0.7, just uploaded to zef!
