### ISSUE TITLE
Default config doesn't match zef's

### ISSUE THREAD

**Issue by patrickbkr** [lizmat/Zef-Configuration#2]
A follow up of https://github.com/ugexe/zef/issues/554

I think Zef-Configuration's factory configuration doesn't match the default zef config. Comparing the two:

Zef's repos:

1. fez
2. cpan (disabled)
3. p6c (disabled)
4. rea
5. cached

Zef-Configuration's repos:

1. fez
2. cpan
3. p6c
4. rea (disabled)
5. cached

The two should match up, or ideally, Zef-Configuration should somehow extract the defaults from zef.

**Comment by lizmat** [comment]
Version 0.11 on its way to the ecosystem now with adjusted defaults.  Thanks for the headsup!
